#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Gerhard Schaden
#
# This file is part of pandoc-linguexx.
#
# pandoc-linguexx is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# pandoc-linguexx is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Build the OnlyOffice plugin: dist/onlyoffice/{GUID}/ and a .plugin.

    python3 tools/build_onlyoffice.py        (or: make onlyoffice)

The add-in's code is ES modules, which the Word task pane loads as they
are.  An OnlyOffice plugin is loaded from local files, where module loading
is not to be relied on, so the same modules are joined here into one
classic script, linguexx.js, exposing a global LinguExx.  Nothing is
rewritten but the module plumbing: each module runs in its own function
scope, `import {a, b as c} from "./x.js"` becomes a lookup in a table of
the modules already run, and `export` becomes an entry in it.  So the code
the plugin runs is the code node --test tests -- and
addin/onlyoffice/test/bundle.test.js checks the bundle against the modules.

The .plugin file is the folder zipped, which OnlyOffice's plugin manager
installs ("Install plugin manually").
"""

from __future__ import annotations

import json
import re
import shutil
import sys
import zipfile
from pathlib import Path, PurePosixPath

ROOT = Path(__file__).resolve().parent.parent
ADDIN = ROOT / "addin"
SRC = ADDIN / "onlyoffice"
GUID = "D71895BD-806D-4964-ACA4-0A531FE92454"
OUT = ROOT / "dist" / "onlyoffice" / f"{{{GUID}}}"
PLUGIN = ROOT / "dist" / "linguexx-onlyoffice.plugin"

#: in dependency order: a module comes after everything it imports
MODULES = [
    "core/constants.js", "core/measure.js", "core/parse.js", "core/plan.js", "core/table.js",
    "core/untypeset.js",
    "word/xml.js", "word/styles.js", "word/ooxml.js", "word/numbering.js",
    "onlyoffice/job.js", "onlyoffice/commands.js",
]

#: what window.LinguExx offers: the plugin's entry points, and a little
#: of the core for looking at things from the console
EXPOSE = {
    "onlyoffice/commands.js": ["readSelection", "insertExample", "listExamples",
                               "completeReference", "readExampleTable", "writeLines"],
    "onlyoffice/job.js": ["prepareJob", "linesFromRead", "stylesJob", "untypesetJob"],
    "core/parse.js": ["parseLines", "strip"],
}

IMPORT = re.compile(r'import\s*\{([^}]*)\}\s*from\s*"([^"]+)";')
EXPORT = re.compile(
    r"^export\s+((?:async\s+)?function\*?|const|let|var|class)\s+([A-Za-z_$][\w$]*)", re.M)


def module_js(name: str) -> str:
    src = (ADDIN / name).read_text(encoding="utf-8")
    here = PurePosixPath(name).parent

    def imp(m: re.Match) -> str:
        target = str((here / m.group(2)).as_posix())
        parts = []
        for spec in m.group(1).split(","):
            spec = spec.strip()
            if not spec:
                continue
            a, _, b = spec.partition(" as ")
            parts.append(f"{a.strip()}: {b.strip()}" if b else a.strip())
        key = str(PurePosixPath(target))
        # normalise "a/../b"
        norm = []
        for piece in key.split("/"):
            if piece == "..":
                norm.pop()
            elif piece != ".":
                norm.append(piece)
        key = "/".join(norm)
        if key not in MODULES[:MODULES.index(name)]:
            sys.exit(f"{name} imports {key}, which is not built before it")
        return f"var {{ {', '.join(parts)} }} = __m[{json.dumps(key)}];"

    src = IMPORT.sub(imp, src)
    names = [m.group(2) for m in EXPORT.finditer(src)]
    src = EXPORT.sub(lambda m: f"{m.group(1)} {m.group(2)}", src)
    if re.search(r"^\s*import\b", src, re.M):
        sys.exit(f"{name}: an import this builder does not understand")
    return (f"// --- {name}\n(function () {{\n{src}\n"
            f"__m[{json.dumps(name)}] = {{ {', '.join(names)} }};\n}})();\n")


def bundle() -> str:
    body = "".join(module_js(m) for m in MODULES)
    expose = ", ".join(f"{n}: __m[{json.dumps(mod)}].{n}"
                       for mod, ns in EXPOSE.items() for n in ns)
    return ("// GENERATED by tools/build_onlyoffice.py from addin/ -- do not edit.\n"
            "// SPDX-License-Identifier: GPL-3.0-or-later\n"
            "var LinguExx = (function () {\n\"use strict\";\nvar __m = {};\n"
            f"{body}return {{ {expose} }};\n}})();\n")


def main() -> int:
    if OUT.exists():
        shutil.rmtree(OUT)
    (OUT / "resources").mkdir(parents=True)
    (OUT / "linguexx.js").write_text(bundle(), encoding="utf-8")
    for f in ("config.json", "index.html", "ui.js"):
        shutil.copy2(SRC / f, OUT / f)
    for f in ("icon.png", "icon@2x.png"):
        shutil.copy2(SRC / "resources" / f, OUT / "resources" / f)
    config = json.loads((OUT / "config.json").read_text(encoding="utf-8"))
    if config["guid"] != f"asc.{{{GUID}}}":
        sys.exit(f"config.json's guid is {config['guid']}, the build says {GUID}")
    PLUGIN.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(PLUGIN, "w", zipfile.ZIP_DEFLATED) as z:
        for path in sorted(OUT.rglob("*")):
            if path.is_file():
                z.write(path, path.relative_to(OUT).as_posix())
    print(f"{OUT.relative_to(ROOT)}/  and  {PLUGIN.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
