#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Gerhard Schaden
#
# This file is part of pandoc-linguexx.
#
# pandoc-linguexx is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# pandoc-linguexx is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Keep the Writer macro's constants identical to the converter's -- and
the JavaScript add-in core's.

The macro is Basic and the add-in core is a browser module; neither can
import anything from here, so the style names, layout lengths and measured
advance widths exist three times.  This writes the other two copies from
the first: the generated block of LinguExx.bas, and all of
addin/core/constants.js -- and, for the Word add-in, addin/word/styles.js,
the very style definitions the converter injects into a .docx.

    python3 tools/sync_macro.py            # check, exit 1 on drift
    python3 tools/sync_macro.py --write    # rewrite the generated block

``tests/test_macro_sync.py`` runs the check, so drift fails the suite
rather than surfacing as an example that is a millimetre out.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

import dataclasses  # noqa: E402
import json  # noqa: E402

from linguexx2odt import measure, styles_docx  # noqa: E402
from linguexx2odt.styles import (  # noqa: E402
    Layout, MACRO_LENGTHS, MACRO_NAMES, MACRO_NOT_SHARED,
)

MACRO = ROOT / "src" / "linguexx2odt" / "writermacro" / "LinguExx.bas"
BEGIN = "' --- BEGIN GENERATED — see tools/sync_macro.py; do not edit by hand"
END = "' --- END GENERATED"


def block() -> str:
    """The Basic declarations implied by styles.py."""
    layout = Layout()
    width = max(len(n) for n in list(MACRO_NAMES) + list(MACRO_LENGTHS))
    out = [
        BEGIN,
        "'",
        "' Style names and layout lengths shared with the converter, so that a",
        "' converted example and a macro-built one are the same object and",
        "' answer to the same styles.  Regenerate with:",
        "'",
        "'     python3 tools/sync_macro.py --write",
        "'",
    ]
    for name, value in MACRO_NAMES.items():
        out.append(f'Const {name:<{width}} As String = "{value}"')
    out.append("")
    out.append("' In centimetres, from linguexx2odt.styles.Layout.")
    for name, attr in MACRO_LENGTHS.items():
        out.append(f"Const {name:<{width}} As Double = {getattr(layout, attr)}")
    out.append("")
    out.append("' Deliberately not shared:")
    for attr, why in MACRO_NOT_SHARED.items():
        out.append(f"'   {attr} — {why}")
    out.append(END)
    return "\n".join(out)


JS = ROOT / "addin" / "core" / "constants.js"


def js_constants() -> str:
    """addin/core/constants.js, whole: everything the core must agree on.

    Every Layout default rather than the macro's selection of them: the
    core estimates as the converter does, so width_safety and font_pt are
    its business too.  The advance table is the one measure.py estimates
    with, so a column the core sizes and one the converter sizes are the
    same width for the same words.
    """
    layout = {f.name: getattr(Layout(), f.name) for f in dataclasses.fields(Layout)}

    def dump(value) -> str:
        # Readable, except for what cannot be read: a raw no-break space or
        # soft hyphen as a key is a character nobody can see and somebody
        # will one day "fix".
        text = json.dumps(value, ensure_ascii=False, indent=2, sort_keys=False)
        return text.replace("\u00a0", "\\u00a0").replace("\u00ad", "\\u00ad")

    return "\n".join([
        "// GENERATED by tools/sync_macro.py from src/linguexx2odt/styles.py",
        "// and measure.py -- do not edit by hand.  Regenerate with:",
        "//",
        "//     python3 tools/sync_macro.py --write      (or: make macro)",
        "//",
        "// tests/test_macro_sync.py fails when this file and its sources drift.",
        "",
        "/** Paragraph-style and sequence names, as the macro's Const block. */",
        f"export const NAMES = Object.freeze({dump(MACRO_NAMES)});",
        "",
        "/** Every default of styles.Layout; lengths in centimetres. */",
        f"export const LAYOUT = Object.freeze({dump(layout)});",
        "",
        "/** Advance widths in em, measured from Liberation Serif (measure._ADVANCE). */",
        f"export const ADVANCE = Object.freeze({dump(measure._ADVANCE)});",
        "",
        f"export const FALLBACK_UPPER = {measure._FALLBACK_UPPER};",
        f"export const FALLBACK_OTHER = {measure._FALLBACK_OTHER};",
        "",
        "/** Faces measured from their font files (measure._FACE_ADVANCE), by key. */",
        f"export const FACE_ADVANCE = Object.freeze({dump(measure._FACE_ADVANCE)});",
        "",
        "/** Faces that share Times metrics, so ADVANCE describes them. */",
        f"export const TIMES_METRIC = Object.freeze({dump(sorted(measure.TIMES_METRIC))});",
        "",
        "/** Grid.TOL: column boundaries closer than this (cm) are one boundary. */",
        f"export const GRID_TOL = {measure.Grid.TOL};",
        "",
    ])


WORD_STYLES = ROOT / "addin" / "word" / "styles.js"


def js_word_styles() -> str:
    """addin/word/styles.js: the converter's .docx styles, verbatim.

    An example the add-in inserts and one the converter wrote must answer
    to the same styles, or restyling LxExampleCell in the Styles pane moves
    one and not the other.  So the add-in carries styles_fragment() itself,
    not a transcription of it.  The document-default face is deliberately
    NOT carried: the converter sets it because it writes the whole document,
    and an add-in must not change the face of somebody else's prose.
    """
    fragment = styles_docx.styles_fragment(Layout())
    ids = re.findall(r'w:styleId="([^"]+)"', fragment)
    return "\n".join([
        "// GENERATED by tools/sync_macro.py from src/linguexx2odt/styles_docx.py",
        "// -- do not edit by hand.  Regenerate with: make macro",
        "",
        "/** Every style an example uses: styles_docx.styles_fragment(Layout()). */",
        f"export const STYLES_FRAGMENT = {json.dumps(fragment)};",
        "",
        "/** Their ids, in the order the fragment declares them. */",
        f"export const STYLE_IDS = Object.freeze({json.dumps(ids)});",
        "",
        f"export const LEIPZIG_CHAR = {json.dumps(styles_docx.LEIPZIG_CHAR)};",
        f"export const ESTIMATED_FONT = {json.dumps(styles_docx.ESTIMATED_FONT)};",
        "",
    ])


#: every JavaScript file this writes, and what writes it
GENERATED_JS = {JS: js_constants, WORD_STYLES: js_word_styles}


def current(source: str) -> str:
    m = re.search(re.escape(BEGIN) + r".*?" + re.escape(END), source, re.S)
    if not m:
        sys.exit(
            f"{MACRO}: no generated block found.\n"
            f"Add these two lines around the Const declarations:\n"
            f"  {BEGIN}\n  {END}"
        )
    return m.group(0)


def main(argv: list[str]) -> int:
    write = "--write" in argv
    drifted = 0

    source = MACRO.read_text(encoding="utf-8")
    have, want = current(source), block()
    if have == want:
        print(f"{MACRO.name}: in sync with styles.py")
    elif write:
        MACRO.write_text(source.replace(have, want), encoding="utf-8")
        print(f"{MACRO.name}: generated block rewritten")
    else:
        print("the macro has drifted from src/linguexx2odt/styles.py\n")
        for line in _diff(have, want, MACRO.name):
            print(line)
        drifted += 1

    for path, generate in GENERATED_JS.items():
        have = path.read_text(encoding="utf-8") if path.is_file() else ""
        want = generate()
        rel = path.relative_to(ROOT)
        if have == want:
            print(f"{rel}: in sync with the converter")
        elif write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(want, encoding="utf-8")
            print(f"{rel}: rewritten")
        else:
            print(f"\n{rel} has drifted from the converter\n")
            for line in _diff(have, want, path.name):
                print(line)
            drifted += 1

    if drifted:
        print("\nrun: python3 tools/sync_macro.py --write")
    return 1 if drifted else 0


def _diff(have: str, want: str, name: str):
    import difflib
    return difflib.unified_diff(
        have.splitlines(), want.splitlines(),
        fromfile=name, tofile="styles.py", lineterm="",
    )


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
